{% set name = "recurring-ical-events" %}
{% set version = "3.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/recurring_ical_events-{{ version }}.tar.gz
  sha256: c3eb2490a00559fb963d2bdee39acf2f287c91c07dcea4ce80ade1c60a8c3acf


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - icalendar >=6.1.0,<7.0.0
    - python-dateutil >=2.8.1,<3.0.0
    - x-wr-timezone >=1.0.0,<3.0.0
    - python-tzdata
    - typing-extensions


test:
  imports:
    - recurring_ical_events
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/niccokunzmann/python-recurring-ical-events
  summary: A Python module which repeats ICalendar events by RRULE, RDATE and EXDATE.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdido
